import fs from 'node:fs';
import { SCENE_CATALOG, verifyCatalogAssets } from '../server/catalog.mjs';

verifyCatalogAssets();
// The editable sources are config/characters.json and config/scenes.json.
// Clients receive presentation data only; role instructions stay on the server.
const scenes = SCENE_CATALOG.map(({ roleInstruction, character, ...scene }) => {
  const { background, ...profile } = character;
  return { ...scene, character: {
    ...profile,
    personality: { tags: character.personality.tags },
    speakingStyle: { label: character.speakingStyle.label },
  } };
});
const code = `// Generated by npm run sync:catalog. Edit config/*.json, not this file.\n(function (root, factory) {\n  const scenes = factory();\n  if (typeof module === 'object' && module.exports) module.exports = scenes;\n  else root.SpeakingScenes = scenes;\n})(typeof globalThis !== 'undefined' ? globalThis : this, function () {\n  return ${JSON.stringify(scenes, null, 2)};\n});\n`;
for (const file of ['../public/scenes.js', '../miniprogram/utils/scenes.js']) {
  const target = new URL(file, import.meta.url);
  if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== code) fs.writeFileSync(target, code);
}
const rows = SCENE_CATALOG.map(scene => {
  const c = scene.character;
  return `| ${c.name} | ${c.genderLabel} · ${c.age} 岁 | ${scene.title} / ${c.occupation} | ${c.personality.tags.join('、')} | ${c.voice.id} | ${c.speakingStyle.label} |`;
});
const profiles = SCENE_CATALOG.map(scene => {
  const c = scene.character;
  return `## ${c.name}\n\n- 稳定 ID：\`${c.id}\`；档案版本：${c.version}；场景 ID：\`${scene.id}\`。\n- 基础信息：${c.genderLabel}，${c.age} 岁，${c.occupation}，代词 ${c.pronouns}。\n- 画像：${c.bio}\n- 爱好：${c.interests.join('、')}。\n- 外观：${c.appearance.description}\n- 图片位置：3×2 图集坐标 (${c.appearance.spriteX}, ${c.appearance.spriteY})。\n- 性格：${c.personality.tags.join('、')}。\n- 音色：\`${c.voice.id}\`；表达风格：${c.speakingStyle.label}。\n- 背景提示词：${c.background}\n- 性格提示词：${c.personality.instruction}\n- 表达提示词：${c.speakingStyle.instruction}\n`;
});
const doc = `# AI口语搭子 · 人物档案\n\n由 \`npm run sync:catalog\` 从配置自动生成。所有年龄、身份和经历都是产品创作的虚构设定；图片是 3D 风格插画。\n\n| 人物 | 基础信息 | 场景与身份 | 性格 | 千问 voice ID | 声音与表达方向 |\n| --- | --- | --- | --- | --- | --- |\n${rows.join('\n')}\n\n六人使用六种不同的预设音色，按当前图片的成年人物设定选配。音色能力依据 [千问官方音色列表](https://help.aliyun.com/zh/model-studio/omni-voice-list) 的 Qwen3.8 专属章节，核对日期 2026-10-02。音色描述用于初选，真实听感与人物贴合度仍需逐个试听；提示词只调整语气，不代替音色选择。\n\n${profiles.join('\n')}\n## 维护方法\n\n1. 只改 \`config/characters.json\` 中对应角色。姓名、性别、年龄、性格、背景、爱好、说话方式、voiceId、图片位置都在同一条记录中。角色 ID 保持稳定，修改档案后递增 version。\n2. 场景单独维护在 \`config/scenes.json\`，通过 characterId 引用角色、displayOrder 决定首页排序。新增场景可以复用同一人物，不复制人设。图片沿用 3×2 图集规则；更换图集需同时放入网页和小程序的 assets 目录。\n3. 执行 \`npm run sync:catalog\`，生成网页、小程序的目录与本文件；执行 \`npm test\`，然后重新启动后端、刷新网页或重新编译小程序。\`npm start\` 也会自动同步。\n4. 更换声音时，先在 voices 中登记当前模型支持的准确 ID、声音性别、语言和官方来源，再改人物的 voiceId。旧的 .env QWEN_VOICE 已不参与角色选择，避免把所有人覆盖成同一声音。\n5. 开始新会话时，服务端根据场景选择人物并锁定音色。通话中切换沉浸/语音球画面不会换人或重连；换人物需要结束当前通话再进入另一个场景。\n\n程序启动时校验重复 ID、断开的场景引用、性别与音色对应及图片映射；错误会明确失败，不静默退回统一女声。session.ready 返回角色 ID、名字、档案版本和 voice ID 的快照，便于未来扩展历史记录。当前不新增跨会话记忆、聊天记录存储、声音克隆或后台管理系统。\n`;
fs.mkdirSync(new URL('../docs/', import.meta.url), { recursive: true });
fs.writeFileSync(new URL('../docs/角色档案.md', import.meta.url), doc);
console.log(`已同步 ${scenes.length} 个场景与人物档案。`);
